---
output: github_document
bibliography: inst/REFERENCES.bib
link-citations: yes
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# wrongabbreviation

<!-- badges: start -->

<!-- badges: end -->

The goal of wrongabbreviation [@igraph] is to ...

## Installation

You can install the development version of wrongabbreviation from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("dieghernan/wrongabbreviation")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(wrongabbreviation)
## basic example code
```

## Citation

```{r echo=FALSE, results='asis'}
print(citation("wrongabbreviation")[1], bibtex = FALSE)
```

A BibTeX entry for LaTeX users is

```{r echo=FALSE, comment=''}
toBibtex(citation("wrongabbreviation")[1])
```

## References

::: {#refs}
:::
